services:
  hc:
    image: hc
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_network
      traefik.http.routers.hc.tls: true
      traefik.http.routers.hc.rule: Host(`hc.${BASE_URL}`) || Host(`hc.sylnt.us`)
      traefik.http.routers.hc.entrypoints: websecure
      traefik.http.routers.hc.service: www-hc-service
      traefik.http.routers.hc.tls.certresolver: myresolver
      traefik.http.services.www-hc-service.loadbalancer.server.port: 8000
    environment:
     - ADMINS
     - DB_NAME=/data/hc.sqlite
     - ALLOWED_HOST
     - DB
     - DEFAULT_FROM_EMAIL
     - EMAIL_HOST=mail.soylentnews.org
     - EMAIL_PORT=465
     - EMAIL_USE_TLS=True
     - EMAIL_USE_VERIFICATION=False
     - EMAIL_HOST_PASSWORD
     - EMAIL_HOST_USER
     - INTEGRATIONS_ALLOW_PRIVATE_IPS
     - PING_EMAIL_DOMAIN
     - SMTPD_PORT
     - REGISTRATION_OPEN
     - SHELL_ENABLED
     - SITE_NAME
     - SITE_ROOT
    volumes:
      - /opt/hc:/data
    networks:
     - traefik
networks:
 traefik:
  name: traefik_network
  external: true
