version: "3"
services:
 kiwiirc:
  image: sn_kiwiirc
  restart: always
  entrypoint: ["/bin/sh", "-c", "echo '192.163.30.227 irc.soylentnews.org' >> /etc/hosts && su -c './kiwiirc' devop"]
  environment:
   - HTTP_PORT=80
  networks:
   - traefik
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=traefik_network"
   - "traefik.http.routers.kiwi.tls=true"
   - "traefik.http.routers.kiwi.rule=Host(`irc.${BASE_URL}`)"
   - "traefik.http.routers.kiwi.entrypoints=websecure"
   - "traefik.http.routers.kiwi.service=kiwi-service"
   - "traefik.http.routers.kiwi.tls.certresolver=myresolver"
   - "traefik.http.services.kiwi-service.loadbalancer.server.port=80"
  volumes:
   - /opt/kiwiirc/config.json:/app/www/static/config.json
   - /opt/kiwiirc/config.conf:/app/config.conf
networks:
 traefik:
  external: true
  name: traefik_network
