version: "3"
services:
 mediawiki:
  image: sn_mediawiki:REL1_41
  restart: always
  environment:
   - BASE_URL
   - MYSQL_DATABASE=${MYSQL_DB}
   - MARIADB_DATABASE=${MYSQL_DB}
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MARIADB_USER
   - MARIADB_PASSWORD
#  ports:
#   - 80:80
  links:
   - database
  networks:
   - traefik
   - mediawiki-db
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=traefik_network"
   - "traefik.http.routers.mediawiki.tls=true"
   - "traefik.http.routers.mediawiki.rule=Host(`wiki.${BASE_URL}`)"
   - "traefik.http.routers.mediawiki.entrypoints=websecure"
   - "traefik.http.routers.mediawiki.service=www-media-service"
   - "traefik.http.routers.mediawiki.tls.certresolver=myresolver"
   - "traefik.http.services.www-media-service.loadbalancer.server.port=80"
  volumes:
   - /opt/mediawiki/images:/var/www/html/images
   - ./LocalSettings.php:/var/www/html/LocalSettings.php
 backup:
  build:
   context: ./db-backup/
  depends_on:
   - database
  restart: always
  networks:
   - mediawiki-db
  environment:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MARIADB_USER
   - MARIADB_PASSWORD
   - MYSQL_HOST=database
   - MYSQL_DB
   - ENCRYPT_PASSWORD
  volumes:
   - /opt/mediawiki/backup:/backup

 database:
  image: mariadb
  restart: always
  networks:
   - mediawiki-db
  environment:
   - MYSQL_DATABASE=${MYSQL_DB}
   - MARIADB_DATABASE=${MYSQL_DB}
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MARIADB_USER
   - MARIADB_PASSWORD
   - MARIADB_ROOT_PASSWORD
  volumes:
   - /opt/mediawiki/db:/var/lib/mysql
networks:
 traefik:
  name: traefik_network
 mediawiki-db:
