services:
  db:
    # 10.11 is the current lts
    image: mariadb:10.11
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=powerdnsadmin
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD
    restart: always
    networks:
     - default
    volumes:
      - /opt/dns/mysql/:/var/lib/mysql
  pdns:
    image: sn_pdns
    hostname: ns0.${BASE_URL}
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    links:
      - "db:db"
    networks:
     - traefik
     - default
    ports:
      - "53:53"
      - "53:53/udp"
#      - "8081:8081"
    environment:
      - PDNS_gmysql_host=db
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=pdns
      - PDNS_gmysql_dbname=powerdnsadmin
      - PDNS_gmysql_password
      - PDNS_gmysql_dnssec=yes
      - PDNS_secondary=yes
      - PDNS_primary=yes
      - PDNS_api=yes
      - PDNS_api_key
      - PDNSCONF_API_KEY
      - PDNS_webserver=yes
      - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24,47.180.135.56/32
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_notify_from=0.0.0.0,50.116.25.207,172.31.0.1
      - PDNS_allow_axfr_ips=127.0.0.1,2600:3c00::f03c:91ff:fe6e:1d88,50.116.25.207
  admin:
    image: sn_pdns_admin
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_ADMIN_SQLA_DB_USER=pdns
      - PDNS_ADMIN_SQLA_DB_PASSWORD
      - PDNS_ADMIN_SQLA_DB_HOST=db
      - PDNS_VERSION=4.8
      - PDNS_API_URL="http://pdns:8081/"
      - PDNS_API_KEY
    depends_on:
      - db
    restart: always
    links:
      - "db:db"
      - "pdns:pdns"
    logging:
      driver: json-file
      options:
        max-size: 50m
    labels:
     traefik.enable: true
     traefik.docker.network: traefik_network
     traefik.http.routers.dns-web.tls: true
     traefik.http.routers.dns-web.rule: Host(`dns.${BASE_URL}`)
     traefik.http.routers.dns-web.entrypoints: websecure
     traefik.http.routers.dns-web.service: dns-web-service
     traefik.http.routers.dns-web.tls.certresolver: myresolver
     traefik.http.services.dns-web-service.loadbalancer.server.port: 8080
    networks:
     - traefik
     - default
networks:
 traefik:
  name: traefik_network
  external: true
 default:
