version: '3.1'

services:
  eggdrop:
    env_file:
     - .env
    build:
     context: ./eggbot
    command: ["Regurgitator.conf"]
    ports:
     - "3333:3333"
    volumes:
     - /opt/eggbot/data/:/home/eggdrop/eggdrop/data/
     - /opt/eggbot/logs/:/home/eggdrop/eggdrop/logs/
     - ./scripts/:/home/eggdrop/eggdrop/scripts/

### If you want to add scripts, put them here. Don't mount to /scripts because
### it will overwrite the ones that are already used. Make sure you use 
### 'source scripts2/foo.tcl' as the path in the config.
#     - /changethispart/scripts:/home/eggdrop/eggdrop/scripts2
### Enter config name, if not eggdrop.conf
#    command: LeafBlower.conf
    stdin_open: true
    tty: true
    restart: always
