version: '3'

services:
 reverse-proxy:
  image: traefik:v2.10
  restart: always
  command:
   - "--api.dashboard=true"
   - "--providers.docker=true"
   - "--providers.docker.exposedbydefault=false"
   - "--providers.file.directory=/config"
   - "--providers.file.watch=true"
   - "--entrypoints.websecure.address=:443"
   - "--entrypoints.ircd.address=:7000"
   - "--entrypoints.api.address=:8080"
   - "--entrypoints.api.http.tls=true"
   - "--entrypoints.ircd2.address=:6697"
   - "--entrypoints.web.address=:80"
   - "--entrypoints.monweb.address=:8000"
   - "--entrypoints.xmlrpc.address=:8081"
   - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
   - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
   - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
   - "--certificatesresolvers.myresolver.acme.email=justin.ennen@ennwise.com"
   - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  labels:
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USERS}"
      - "traefik.http.routers.api.rule=Host(`traefik.testing.soylentnews.org`)"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.routers.api.entrypoints=api"
      - "traefik.enable=true"
  ports:
   - "192.163.30.227:443:443"
   - "192.163.30.227:8080:8080"
   - "192.163.30.227:8081:8081"
   - "192.163.30.227:7000:7000"
   - "192.163.30.227:8000:8000"
   - "192.163.30.227:80:80"
   - "[2602:fd63:12::2]:443:443"
   - "[2602:fd63:12::2]:8080:8080"
   - "[2602:fd63:12::2]:8081:8081"
   - "[2602:fd63:12::2]:7000:7000"
   - "[2602:fd63:12::2]:8000:8000"
   - "[2602:fd63:12::2]:80:80"
# - "6697:6697"
  networks:
   - traefik
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
   - "/opt/letsencrypt:/letsencrypt"
   - "/opt/traefik/:/config"
 dump-certs:
   restart: always
   image: ldez/traefik-certs-dumper:v2.8.1
   container_name: traefik-certs-dumper
   environment:
    BASE_URL: testing.soylentnews.org
   entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /data/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
        --source /data/acme.json --dest /data/certs
        --post-hook "sh /hook.sh"'
   labels:
    traefik.enable: false
   volumes:
    - "/opt/letsencrypt:/data"
    - ./hook.sh:/hook.sh
networks:
 traefik:
  name: traefik_network
  enable_ipv6: true
