version: "3"
services:
 rehash:
  image: sn_rehash
  build:
   context: ./rehash/
  environment:
    MYSQL_HOST: database
#    MYSQL_USER: 
#    MYSQL_PASSWORD: 
    MYSQL_DATABASE: soylentnews
    ENABLE_MAIL: "true"
    MYHOSTNAME: soylentnews.org
    RELAYHOST: postfix
  restart: always
  depends_on:
   - database
  env_file:
   - /secrets/production.env
  links:
   - database
   - sphinx
  networks:
   - varnish
   - rehash-db
  volumes:
   - /opt/rehash/logs:/srv/soylentnews.logs
 backup:
  build:
   context: ./db-backup/
  depends_on:
   - database
  restart: always
  env_file:
   - /secrets/production.env
  networks:
   - rehash-db
  environment:
#  MYSQL_USER
#  MYSQL_PASSWORD
   MYSQL_HOST: database
   MYSQL_DB: soylentnews
#  ENCRYPT_PASSWORD
  volumes:
   - /opt/rehash/backup:/backup
 db-view:
  image: phpmyadmin/phpmyadmin:latest
  environment:
   PMA_HOST: database
   PMA_PORT: 3306
  networks:
   - rehash-db
   - traefik
  restart: always
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=traefik_network"
   - "traefik.http.routers.db-view.tls=true"
   - "traefik.http.routers.db-view.rule=Host(`db-view.${BASE_URL}`)"
   - "traefik.http.routers.db-view.entrypoints=websecure"
   - "traefik.http.routers.db-view.service=db-view-service"
   - "traefik.http.routers.db-view.tls.certresolver=myresolver"
   - "traefik.http.services.db-view-service.loadbalancer.server.port=80"
   - "traefik.http.routers.db-view.middlewares=db-view-auth"
   - "traefik.http.middlewares.db-view-auth.basicauth.users=${DB_VIEW_USERS}"
 database:
  build:
   context: ./sn_mariadb/
   dockerfile: sn_mariadb.yml
  image: sn_mariadb
  restart: always
  networks:
   - rehash-db
  env_file:
   - /secrets/production.env
  environment:
   MYSQL_DATABASE: soylentnews
#   MYSQL_USER:
#   MYSQL_PASSWORD:
#   MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  volumes:
   - /opt/rehash/db:/var/lib/mysql

 varnish:
  image: varnish:stable
#  container_name: varnish
  volumes:
    - ./soylentnews.vcl:/etc/varnish/default.vcl
  ports:
    - "2600:80"
  networks:
   - traefik
   - varnish
  links:
   - rehash
  tmpfs:
   - /var/lib/varnish:exec
  environment:
   - VARNISH_SIZE=2G
  command: "-p default_keep=300"
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=traefik_network"
   - "traefik.http.routers.rehash.tls=true"
   - "traefik.http.routers.rehash.rule=Host(`www.${BASE_URL}`) || Host(`${BASE_URL}`) || Host(`paypal.${BASE_URL}`)"
   - "traefik.http.routers.rehash.entrypoints=websecure"
   - "traefik.http.routers.rehash.service=www-rehash-service"
   - "traefik.http.routers.rehash.tls.certresolver=myresolver"
   - "traefik.http.services.www-rehash-service.loadbalancer.server.port=80"
 sphinx:
  image: sphinx
  build:
    context: ./sphinx
    dockerfile: Dockerfile
  restart: always
  networks:
   - rehash-db
  volumes:
   - /opt/sphinx:/sphinx
  depends_on:
   - database
  env_file:
   - /secrets/production.env
  environment:
   MYSQL_HOST: database
#   MYSQL_USER:
#   MYSQL_PASSWORD:
   MYSQL_DATABASE: soylentnews

networks:
 traefik:
  name: traefik_network
  external: true
 rehash-db:
 varnish:

