message_templates = {
    "light": [
        "{attacker} gives {defender} a gentle pat on the {location} with their {weapon}, causing {damage} damage. It's almost affectionate!",
        "With a feather-light touch, {attacker} manages to {effectiveness} annoy {defender} in the {location} using their {weapon}, dealing {damage} damage.",
        "{attacker} lands a playful slap on {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. Was that a fight or a tickle?",
        "{defender} barely feels the light tap from {attacker}'s {weapon} on their {location}, but it still causes {damage} damage.",
        "{attacker} lightly taps {defender} on the {location} with their {weapon}, causing {damage} damage. A true masterpiece of gentleness!",
        "With the grace of a dancer, {attacker} gently brushes {defender}'s {location} with their {weapon}, dealing {damage} damage.",
        "{attacker} barely caresses {defender}'s {location} with their {weapon}, but it somehow results in {damage} damage.",
        "In a move that could be mistaken for a hug, {attacker} softly hits {defender} in the {location} with their {weapon}, causing {damage} damage.",
        "{attacker} gives a friendly nudge to {defender}'s {location} with their {weapon}, resulting in {damage} damage. So considerate!",
        "With the precision of a lullaby, {attacker} gently strikes {defender} in the {location} with their {weapon}, causing {damage} damage.",
        "{attacker} tickles {defender}'s {location} with their {weapon}, dealing {damage} damage and leaving them confused.",
        "Like a leaf falling, {attacker} lands a delicate blow on {defender}'s {location} with their {weapon}, causing {damage} damage.",
        "{attacker} gives a soft boop to {defender}'s {location} with their {weapon}, resulting in {damage} damage.",
        "With the finesse of a feather, {attacker} taps {defender}'s {location} with their {weapon}, causing {damage} damage.",
        "{attacker} delivers a light touch to {defender}'s {location} with their {weapon}, dealing {damage} damage. Was that a mosquito?",
        "In a barely-there move, {attacker} grazes {defender}'s {location} with their {weapon}, causing {damage} damage.",
        "{attacker} softly pets {defender}'s {location} with their {weapon}, resulting in {damage} damage. How affectionate!",
        "With the softness of a cloud, {attacker} lands a light blow on {defender}'s {location} with their {weapon}, causing {damage} damage.",
        "{attacker} gently flicks {defender}'s {location} with their {weapon}, dealing {damage} damage and a slight sense of surprise."
    ],
    "moderate": [
        "{attacker} swings with moderate force, hitting {defender} in the {location} with their {weapon} and {effectiveness} causing {damage} damage.",
        "A decent hit from {attacker} lands on {defender}'s {location} with their {weapon}, {effectiveness} resulting in {damage} damage. Not bad!",
        "{attacker} delivers a solid punch to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That'll leave a mark!",
        "{defender} winces as {attacker} {effectiveness} strikes their {location} with their {weapon}, dealing {damage} damage.",
        "{attacker} channels their inner warrior and {effectiveness} strikes {defender} in the {location} with their {weapon}, causing {damage} damage.",
        "With a battle cry, {attacker} {effectiveness} hits {defender} in the {location} with their {weapon}, dealing {damage} damage.",
        "{attacker} lands a respectable blow on {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. A solid effort!",
        "In a move worthy of a training montage, {attacker} {effectiveness} strikes {defender} in the {location} with their {weapon}, causing {damage} damage.",
        "{attacker} delivers a moderately epic hit to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage.",
        "With the precision of a seasoned fighter, {attacker} {effectiveness} hits {defender} in the {location} with their {weapon}, dealing {damage} damage.",
        "{attacker} swings their {weapon} with moderate force, {effectiveness} hitting {defender} in the {location} and causing {damage} damage.",
        "A well-aimed strike from {attacker} lands on {defender}'s {location} with their {weapon}, {effectiveness} resulting in {damage} damage.",
        "{attacker} delivers a solid hit to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That'll smart!",
        "With a determined look, {attacker} {effectiveness} strikes {defender} in the {location} with their {weapon}, dealing {damage} damage.",
        "{attacker} channels their focus and {effectiveness} hits {defender} in the {location} with their {weapon}, causing {damage} damage. A commendable strike!"
    ],
    "heavy": [
        "{attacker} delivers a heavy blow to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. Ouch, that's gotta hurt!",
        "With a powerful swing, {attacker} {effectiveness} smashes {defender} in the {location} with their {weapon}, dealing {damage} damage.",
        "{attacker} lands a crushing hit on {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That was brutal!",
        "{defender} staggers as {attacker} {effectiveness} slams into their {location} with their {weapon}, dealing {damage} damage.",
        "{attacker} delivers a thunderous blow to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That's gotta leave a mark!",
        "With the power of a freight train, {attacker} {effectiveness} smashes {defender} in the {location} with their {weapon}, dealing {damage} damage.",
        "{attacker} lands a bone-crushing hit on {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That was intense!",
        "{attacker} slams into {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. Feel the earth shake!",
        "With a Herculean effort, {attacker} {effectiveness} pummels {defender} in the {location} with their {weapon}, dealing {damage} damage. Legendary!",
        "{attacker} brings their {weapon} down on {defender}'s {location} with all their might, {effectiveness} causing {damage} damage. Total destruction!",
        "{attacker} hammers {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. No mercy!",
        "{attacker} crushes {defender} in the {location} with their {weapon}, {effectiveness} causing {damage} damage. It's hammer time!",
        "With the force of a hurricane, {attacker} {effectiveness} hits {defender} in the {location} with their {weapon}, dealing {damage} damage. What a storm!",
        "{attacker} smashes {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That hit like a truck!",
        "{attacker} pounds {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That was brutal!",
        "With a massive swing, {attacker} {effectiveness} strikes {defender} in the {location} with their {weapon}, dealing {damage} damage. An epic hit!",
        "{attacker} brings the pain to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. Unstoppable!",
        "In a move that could level a mountain, {attacker} {effectiveness} smashes {defender} in the {location} with their {weapon}, dealing {damage} damage. Boom!",
        "{attacker} delivers a powerful blow to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That one's gonna sting!"
    ],
    "critical": [
        "{attacker} lands a jaw-dropping critical hit on {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. Kaboom!",
        "With deadly precision, {attacker} {effectiveness} strikes {defender}'s {location} with their {weapon}, dealing {damage} damage. Critical impact!",
        "{attacker} delivers a mind-blowing hit to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. You won't believe this!",
        "In a move of sheer brilliance, {attacker} {effectiveness} hits {defender}'s {location} with their {weapon}, dealing {damage} damage. Epic!",
        "{attacker} executes a flawless strike on {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. Perfection!",
        "{attacker}'s {weapon} finds its mark on {defender}'s {location} with uncanny accuracy, {effectiveness} causing {damage} damage. Legendary!",
        "Like a bolt from the blue, {attacker} {effectiveness} nails {defender}'s {location} with their {weapon}, dealing {damage} damage. Unbelievable!",
        "{attacker} critically clobbers {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That's gotta hurt!",
        "With surgical precision, {attacker} {effectiveness} strikes {defender}'s {location} with their {weapon}, causing {damage} damage. What a hit!",
        "In an astonishing display of skill, {attacker} {effectiveness} lands a critical hit on {defender}'s {location} with their {weapon}, causing {damage} damage. Bravo!",
        "{attacker} pulls off an insane hit on {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. Unstoppable!",
        "With an unbelievable swing, {attacker} {effectiveness} hits {defender}'s {location} with their {weapon}, dealing {damage} damage. That's a showstopper!",
        "{attacker} finds the sweet spot on {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. What a move!",
        "In a moment of pure brilliance, {attacker} {effectiveness} strikes {defender}'s {location} with their {weapon}, dealing {damage} damage. Amazing!",
        "{attacker} delivers a critical blow to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. A stunning hit!",
        "{attacker} lands a critical hit on {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. It's super effective!",
        "With pinpoint accuracy, {attacker} {effectiveness} strikes {defender} in the {location} with their {weapon}, dealing {damage} damage. Critical hit!",
        "{attacker} delivers a devastating blow to {defender}'s {location} with their {weapon}, {effectiveness} causing {damage} damage. That was epic!",
        "{defender} is critically hit by {attacker} in the {location} with their {weapon}, {effectiveness} suffering {damage} damage. What a hit!"
    ],
    "defense": [
        "{defender}'s {armor} absorbs most of the impact from {attacker}'s {weapon}, reducing the damage to {damage}.",
        "Thanks to their {armor}, {defender} barely feels the strike from {attacker}'s {weapon} on their {location}, taking only {damage} damage.",
        "{attacker} struggles to penetrate {defender}'s {armor} with their {weapon}, causing only {damage} damage.",
        "{defender}'s {armor} solidly deflects the hit from {attacker}'s {weapon}, resulting in {damage} damage.",
        "{defender}'s {armor} absorbs most of the impact from {attacker}'s {weapon}, reducing the damage to {damage}. A true shield!",
        "Thanks to their {armor}, {defender} barely feels the strike from {attacker}'s {weapon} on their {location}, taking only {damage} damage. Rock solid!",
        "{attacker} struggles to penetrate {defender}'s {armor} with their {weapon}, causing only {damage} damage. Nice try!",
        "{defender}'s {armor} solidly deflects the hit from {attacker}'s {weapon}, resulting in {damage} damage. Impressive!",
        "With a clang, {defender}'s {armor} deflects {attacker}'s {weapon}, reducing the damage to {damage}. Steely resolve!",
        "{defender}'s {armor} shrugs off the blow from {attacker}'s {weapon}, causing only {damage} damage. Unbreakable!",
        "{attacker}'s attack glances off {defender}'s {armor}, resulting in {damage} damage. Armor of legends!",
        "Thanks to their trusty {armor}, {defender} withstands the attack from {attacker}'s {weapon}, taking only {damage} damage. Impressive!",
        "In a dazzling display of defense, {defender}'s {armor} absorbs {attacker}'s strike, reducing the damage to {damage}. Invincible!",
        "{defender}'s {armor} blunts the force of {attacker}'s {weapon}, causing only {damage} damage. Ironclad defense!",
        "With a metallic clink, {defender}'s {armor} deflects {attacker}'s attack, reducing the damage to {damage}. Fortified!",
        "{defender}'s {armor} withstands the onslaught from {attacker}'s {weapon}, causing only {damage} damage. Resilient!",
        "Thanks to their formidable {armor}, {defender} brushes off {attacker}'s hit, taking only {damage} damage. Impressive fortitude!",
        "{attacker}'s blow bounces off {defender}'s {armor}, resulting in {damage} damage. Impenetrable!",
        "With the strength of a fortress, {defender}'s {armor} absorbs {attacker}'s attack, reducing the damage to {damage}. Rock steady!"
    ]
}

locations = [
        "head",
        "arm",
        "leg",
        "torso",
        "noggin",
        "funny bone",
        "belly button",
        "pinky toe",
        "love handles",
        "shins",
        "eardrum",
        "elbow",
        "solar plexus",
        "knuckles",
        "tush",
        "big toe",
        "ears",
        "whiskers",
        "gizzard",
        "thumbs",
        "eyebrow",
        "kneecap",
        "spinal cord",
        "cheeks",
        "ankle",
        "ribcage",
        "nostrils",
        "chin",
        "forehead",
        "jawline",
        "backside",
        "pinky finger",
        "calves",
        "collarbone",
        "underarm",
        "inner thigh",
        "forearm",
        "wrists",
        "upper lip",
        "eyelid",
        "collar",
        "hip bone",
        "bottom lip",
        "fingertips",
        "toes",
        "shoulders",
        "upper back",
        "lower back",
        "cheekbones",
        "sideburns",
        "midriff",
        "eyeballs",
        "kneepit",
        "hairline",
        "dimples",
        "jaw",
        "neck",
        "pelvis",
        "tailbone",
        "scalp"
    ]