version: "3"
services:
  loggie:
    image: sn_loggie
    restart: always
    user: root
    entrypoint: ["/custom-entrypoint.sh"]
    environment:
      - LOGGIE_IRCSERVER
      - LOGGIE_IRCPORT
      - LOGGIE_CHANNELS
      - LOGGIE_IRCNICK
      - BASE_URL
    networks:
      - traefik
    volumes:
      - /opt/loggie/logs:/logs
      - ./update-hosts.sh:/update-hosts.sh
      - ./custom-entrypoint.sh:/custom-entrypoint.sh
  httpd:
    image: sn_http
    restart: always
    volumes:
      - /opt/loggie/logs:/usr/local/apache2/htdocs
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_network
      traefik.http.routers.loggie.tls: true
      traefik.http.routers.loggie.rule: Host(`logs.${BASE_URL}`) || Host(`logs.sylnt.us`) || Host(`stats.${BASE_URL}`) || Host(`stats.sylnt.us`)
      traefik.http.routers.loggie.entrypoints: websecure
      traefik.http.routers.loggie.service: www-logs-service
      traefik.http.routers.loggie.tls.certresolver: myresolver
      traefik.http.services.www-logs-service.loadbalancer.server.port: 80
    networks:
      - traefik

networks:
  traefik:
    name: traefik_network
   
