[package]
name = "sn-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
irc = "1.0.0"
regex = "1.11.1"
reqwest = "0.12.21"
rss = "2.0.12"
serde = "1.0.215"
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["full"] }
toml = "0.8.19"
sled = "0.34.7"
